/*
 * File: app/view/MozartMonitor.js
 * Date: Sun May 19 2013 09:44:42 GMT-0700 (PDT)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.MozartMonitor', {
    extend: 'MyApp.view.ui.MozartMonitor',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});