/*
 * File: app/view/ui/MozartMonitor.js
 * Date: Sun May 19 2013 09:44:42 GMT-0700 (PDT)
 *
 * This file was generated by Ext Designer version 1.2.3.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.MozartMonitor', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    height: 500,
                    autoScroll: true,
                    title: 'Mozart Job Monitor',
                    store: 'MozartJsonStore',
                    region: 'north',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'job name'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'queued'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'started'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'ended'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'parameters'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'compute node'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'status'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'duration'
                        }
                    ],
                    viewConfig: {

                    }
                },
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    region: 'center',
                    items: [
                        {
                            xtype: 'panel',
                            title: 'STDOUT'
                        },
                        {
                            xtype: 'panel',
                            title: 'STDERR'
                        },
                        {
                            xtype: 'panel',
                            title: 'Work Dir'
                        },
                        {
                            xtype: 'panel',
                            title: 'Job Info'
                        },
                        {
                            xtype: 'panel',
                            title: 'Context'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }
});